default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  password: postgres
  username: postgres

development:
  <<: *default
  database: go_try_development

test:
  <<: *default
  database: go_try_test

production:
  <<: *default
  database: go_try_production
  username: go_try
  password: <%= ENV['GO_TRY_DATABASE_PASSWORD'] %>
